//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectComprasInventario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class archivos_cotizaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public archivos_cotizaciones()
        {
            this.cotizaciones = new HashSet<cotizaciones>();
            this.cotizacion_proveedor = new HashSet<cotizacion_proveedor>();
        }
    
        public int ID_archivos_cotizaciones { get; set; }
        public string nombreArchivo { get; set; }
        public byte[] archivo { get; set; }
        public int id_tipoCotizacion { get; set; }
    
        public virtual tipoCotizacion tipoCotizacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cotizaciones> cotizaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cotizacion_proveedor> cotizacion_proveedor { get; set; }
    }
}
