//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectComprasInventario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cotizaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cotizaciones()
        {
            this.cotizacion_proveedor = new HashSet<cotizacion_proveedor>();
            this.solicitud_cotizacion = new HashSet<solicitud_cotizacion>();
        }
    
        public int ID_cotizacion { get; set; }
        public int id_usuario { get; set; }
        public int id_archivoCotizacion { get; set; }
        public int id_estado { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual archivos_cotizaciones archivos_cotizaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cotizacion_proveedor> cotizacion_proveedor { get; set; }
        public virtual estado_cotizacion estado_cotizacion { get; set; }
        public virtual usuarios usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<solicitud_cotizacion> solicitud_cotizacion { get; set; }
    }
}
