//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectComprasInventario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cotizacion_proveedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cotizacion_proveedor()
        {
            this.ordenCompra = new HashSet<ordenCompra>();
        }
    
        public int ID_cotizacion_proveedor { get; set; }
        public int id_cotizacion { get; set; }
        public Nullable<int> id_cotizacionRecibida { get; set; }
        public int id_proveedor { get; set; }
        public int id_estado { get; set; }
    
        public virtual archivos_cotizaciones archivos_cotizaciones { get; set; }
        public virtual cotizaciones cotizaciones { get; set; }
        public virtual proveedores proveedores { get; set; }
        public virtual estado_cotizacion_proveedor estado_cotizacion_proveedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ordenCompra> ordenCompra { get; set; }
    }
}
